import { useEffect, useState } from "react";
import { Box, Center } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

import Sidebar from "@/components/Molecules/Sidebar";
import Fonts from "@/components/Atoms/Fonts";
import BgImage from "@/assets/images/BGImageDefault1.png";

import { getAccessToken } from "@/utils";

import type { FC, ReactNode } from "react";

type LayoutProps = {
  children: ReactNode;
  title: string;
};

const Layout: FC<LayoutProps> = ({ children, title }) => {
  const router = useRouter();
  const [isChecking, setChecking] = useState(true);

  useEffect(() => {
    const token = getAccessToken();

    if (token) {
      setChecking(false);
    } else {
      router.push("/");
    }
  }, [router]);

  if (isChecking) {
    return <Center h="100vh">Loading ......</Center>;
  }

  return (
    <>
      <Head>
        <title>{title} | Zodiac Solutions CMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fonts />
      <Box
        as="main"
        bgImage={BgImage.src}
        minH="100vh"
        w="100%"
        bgRepeat="repeat"
        bgSize="auto"
      >
        <Sidebar />
        <Box as="section" marginLeft="250px">
          {children}
        </Box>
      </Box>
    </>
  );
};

export default Layout;
